/*
 * This source file was generated by the Gradle 'init' task
 */
package com.hacp;

import org.junit.Test;

import static org.junit.Assert.assertNotNull;

public class AppTest {
    @Test public void appHasAGreeting() {
        com.hacp.MainApp classUnderTest = new com.hacp.MainApp();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}